apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  namespace: default
  labels:
    app: calculator
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - port: 80           # Internal cluster port
      targetPort: 4000   # Must match containerPort in Deployment
      nodePort: 30080    # External access via this port
      protocol: TCP
